### PR TITLE
Add call drop notebook

### PR DESCRIPTION
**Pull request by tupui**
I did not include the data since it would mean pulling 1GB. We can discuss how this would be shared.

### CODE REVIEW

**Comment by tupui** [comment]
CI is failing because we currently don't include large csv files in the repo (locally everything passes).

@mflaxman10 @patdevinwilson any update on what to do here?

**Comment by tupui** [comment]
@patdevinwilson this is ready for a review. CI is green, it fetches data from the S3 public bucket.

**Comment by tupui** [comment]
We now have an integration with ReviewNB so it's easier to see notebooks https://app.reviewnb.com/heavyai/heavyai-notebooks/pull/2/

**Comment by patdevinwilson** [comment]
<p>LGTM. GH CI was hanging on 'start heavydb' for obvious reasons.</p>

**Comment by tupui** [comment]
Thanks for caching that, there was a bug in the cache path. CI should go back green now otherwise there is an issue.

**Comment by tupui** [comment]
CI is green, merging. Thanks again for the review!

**Comment by patdevinwilson** [comment]
👍

**Pull request merged**
